version: '3.7'
services:
  db:
    image: postgres
    container_name: demat-social-data
    environment:
      POSTGRES_DB: tps_development
      POSTGRES_USER: tps_development
      POSTGRES_PASSWORD: tps_development
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d
  webapp-main:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        port: 3000
    image: demat-social
    container_name: demat-social-app
    environment:
      RAILS_ENV: development
      PORT: 3000
    env_file:
      - docker/dev.env.mandatory
      - docker/.env.optional
    links:
      - db
      - sftp
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - '.:/opt/ds'
      - demat-dev-gems:/opt/ds/tmp/
      - demat-dev-node-modules:/opt/ds/node_modules
  front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        port: 3036
    image: demat-social
    container_name: demat-social-front
    environment:
      RAILS_ENV: development
    command: bundle exec vite dev
    env_file:
      - docker/dev.env.mandatory
      - docker/.env.optional
    ports:
      - '3036:3036'
    volumes:
      - '.:/opt/ds'
      - demat-dev-gems:/opt/ds/tmp/
      - demat-dev-node-modules:/opt/ds/node_modules
  sftp:
    image: atmoz/sftp
    container_name: demat-social-sftp
    volumes:
      - ./sftp_fake/upload:/home/foo
      - ./sftp_fake/ssh_keys/id_rsa.pub:/home/foo/.ssh/keys/id_rsa.pub:ro
    ports:
      - '2222:22'
    command: foo::${UID}
volumes:
  demat-dev-node-modules:
  demat-dev-gems:
  pg-data:
