proxy_cache_path /var/cache/nginx/demat-social levels=1:2 keys_zone=demat-social:10m max_size=1g inactive=7d use_temp_path=off;

log_format upstreamlog '$server_name to: $upstream_addr {$request} '
  'upstream_response_time $upstream_response_time'
  ' request_time $request_time';

upstream demarche-social {
  server webapp-main:3000;
  server webapp-alt:3000;
}

server {
  listen 80 default_server;
  server_name www.demat.social.gouv.fr;
  access_log /var/log/nginx/nginx-access.log upstreamlog;
  
  proxy_cache_key $scheme$request_method$host$request_uri;

  location ~ ^/(assets|images|javascripts|stylesheets|swfs|system)/ {
    set $skip_cache 0;
    try_files $uri @app;
    break;
  }

  location / {
    set $skip_cache 1;
    try_files $uri @app;
  }

  location @app {

    gzip_static on;
    resolver 127.0.0.11 ipv6=off;

    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header X-Cache-Status $upstream_cache_status;
    add_header Cache-Control public;
    add_header Last-Modified "";

    proxy_pass http://demarche-social;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass_request_headers on;
    proxy_buffering on;
    
    proxy_cache demat-social;
    proxy_cache_valid 200 7d;
    proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
    proxy_cache_bypass $skip_cache;
    proxy_no_cache $skip_cache;
  }
}