FROM ruby:2.7

RUN apt update && apt install -y libcurl3-dev libpq-dev zlib1g-dev libssl-dev libreadline-dev zlib1g-dev

# Add node for webpack
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
RUN apt-get update; apt-get install -y yarn

# Chromedriver
RUN curl -fsSL https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_linux64.zip | gunzip > /usr/bin/chromedriver && chmod +x /usr/bin/chromedriver
RUN sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN apt-get update && apt-get install -y google-chrome-stable

RUN mkdir /opt/ds
WORKDIR /opt/ds

EXPOSE $PORT
CMD bash -c "echo 'Container demarré, vous pouvez vous connecter par le CLI' ; while true; do sleep 1 ; done"
