version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: tps_development
      POSTGRES_USER: tps_development
      POSTGRES_PASSWORD: tps_development
    ports:
      - "5432:5432"
    volumes:
      # Ajout du volume qui contient les scripts d'initialisation de la DB lors du lancement du container
      - '../docker:/docker-entrypoint-initdb.d'
  webapp-main:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    env_file:
      - dev.env.mandatory
      - .env.optional
    links:
      - db
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - '..:/opt/ds'
      - demat-dev_gems:/opt/ds/tmp/
      - demat-dev_node-modules:/opt/ds/node_modules
volumes:
  demat-dev_node-modules:
  demat-dev_gems:
