version: "3.7"
services:

  db:
    image: postgres
    #https://hub.docker.com/_/postgres
    environment:
      POSTGRES_DB: tps_prod
      POSTGRES_USER: tps_prod
      POSTGRES_PASSWORD: tps_prod
    ports:
      - "5432:5432"

  webapp-main:
    image: social-gouv-fr/demat:latest
    command:
      - deploy start
    #En l'absence de nginx, service des ressources statiques par le puma + pas de SSL
    environment:
      - RAILS_SERVE_STATIC_FILES=1
      - SSL_FORCE=disabled
      - SENTRY_CURRENT_ENV=local
      - SENTRY_CAPTURE_RATE=1
    env_file:
      - .env.mandatory
      - .env.optional
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    volumes:
      - demat_public_assets:/opt/ds/public
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 0s

  webapp-alt:
    image: social-gouv-fr/demat:latest
    command:
      - start
    #En l'absence de nginx, service des ressources statiques par le puma + pas de SSL
    environment:
      - RAILS_SERVE_STATIC_FILES=1
      - SSL_FORCE=disabled
      - SENTRY_CURRENT_ENV=local
      - SENTRY_CAPTURE_RATE=1
    env_file:
      - .env.mandatory
      - .env.optional
    ports:
      - "3000"
    links:
      - db
    depends_on:
      # Nous avons supprimé db car celui-ci est forcement démarrer avant d'appeler webapp-alt
      # webapp-alt dépend de webapp-main qui dépend de db 
      # => ce qui veut dire que tant que db n'est pas lancé webapp-main ne sera pas lancé et donc webapp-alt aussi vu que webwebapp-alt dépend de webapp-main
      webapp-main:
        condition: service_healthy
    volumes:
      - demat_public_assets:/opt/ds/public:ro

  jobs:
    image: social-gouv-fr/demat:latest
    command:
      - schedule_jobs
    environment:
      - SENTRY_CURRENT_ENV=local
      - SENTRY_CAPTURE_RATE=1
    env_file:
      - .env.mandatory
      - .env.optional
    links:
      - db
    depends_on:
      webapp-main:
        condition: service_healthy
    #Le service job doit envoyer des mails dont le contenu est généré par la précompilation des assets
    volumes:
      - demat_public_assets:/opt/ds/public:ro

  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nginx
      network: host
    depends_on:
      webapp-main:
        condition: service_healthy
    ports:
      - "80:80"

volumes:
  demat_public_assets:
