user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # on cache la version de nginx
    server_tokens off;

    # log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                   '$status $body_bytes_sent "$http_referer" '
    #                   '"$http_user_agent" "$http_x_forwarded_for"';

    log_format main '@@time_local=$time_local'
      '@@remote_addr=$remote_addr'
      '@@remote_user=$remote_user'
      '@@request=$request'
      '@@status=$status'
      '@@body_bytes_sent=$body_bytes_sent'
      '@@http_referrer=$http_referer'
      '@@http_user_agent=$http_user_agent'
      '@@http_x_forwarded_for=$http_x_forwarded_for'
      '@@request_time=$request_time'
      '@@upstream_connect_time=$upstream_connect_time'
      '@@upstream_header_time=$upstream_header_time'
      '@@upstream_response_time=$upstream_response_time'
      '@@source=nginx';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}