default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  timeout: 5000
  database: <%= ENV["DB_DATABASE"] %>
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  variables:
    statement_timeout: <%= ENV['PG_STATEMENT_TIMEOUT'] || 60000 %>

development:
  <<: *default
  # Workaround for https://github.com/ged/ruby-pg/issues/311
  gssencmode: disable

test:
  <<: *default
  # Workaround for https://github.com/ged/ruby-pg/issues/311
  gssencmode: disable

production: &production
  <<: *default
