ministeres:
  - ARS ARA:
      labels:
        - '2023-05-23': "ARS Auvergne-Rhône-Alpes"
  - ARS BFC:
      labels:
        - '2023-05-23': "ARS Bourgogne-Franche-Comté"
  - ARS BRET:
      labels:
        - '2023-05-23': "ARS Bretagne"
  - ARS CVL:
      labels:
        - '2023-05-23': "ARS Centre-Val de Loire"
  - ARS COR:
      labels:
        - '2023-05-23': "ARS Corse"
  - ARS GE:
      labels:
        - '2023-05-23': "ARS Grand Est"
  - ARS GUAD:
      labels:
        - '2023-05-23': "ARS Guadeloupe"
  - ARS GUY:
      labels:
        - '2023-05-23': "ARS Guyane"
  - ARS HDF:
      labels:
        - '2023-05-23': "ARS Hauts-de-France"
  - ARS IF:
      labels:
        - '2023-05-23': "ARS Île-de-France"
  - ARS REU:
      labels:
        - '2023-05-23': "ARS La Réunion"
  - ARS MART:
      labels:
        - '2023-05-23': "ARS Martinique"
  - ARS MAY:
      labels:
        - '2023-05-23': "ARS Mayotte"
  - ARS NORM:
      labels:
        - '2023-05-23': "ARS Normandie"
  - ARS NA:
      labels:
        - '2023-05-23': "ARS Nouvelle-Aquitaine"
  - ARS OCC:
      labels:
        - '2023-05-23': "ARS Occitanie"
  - ARS PDL:
      labels:
        - '2023-05-23': "Pays de la Loire"
  - ARS PACA:
      labels:
        - '2023-05-23': "ARS Provence-Alpes-Côte d'Azur"
  - BCJS:
      labels:
        - '2023-05-23': "Bureau de la communication Jeunesse et sports"
  - DICOM:
      labels:
        - '2023-05-23': "Délégation à l'information et à la communication"
  - DAEI:
      labels:
        - '2023-05-23': "Délégation aux affaires européennes et internationales"
  - DSS:
      labels:
        - '2023-05-23': "Direction de la sécurité sociale"
  - DAJ:
      labels:
        - '2023-05-23': "Direction des affaires juridiques"
  - DFAS:
      labels:
        - '2023-05-23': "Direction des finances, des achats et des services"
  - DRH:
      labels:
        - '2023-05-23': "Direction des ressources humaines des ministères sociaux"
  - DNUM:
      labels:
        - '2023-05-23': "Direction du numérique"
  - DGOS:
      labels:
        - '2023-05-23': "Direction générale de l’offre de soins"
  - DGCS:
      labels:
        - '2023-05-23': "Direction générale de la cohésion sociale"
  - DGS:
      labels:
        - '2023-05-23': "Direction générale de la santé"
  - SG:
      labels:
        - '2023-05-23': "Secrétariat général des ministères chargés des affaires sociales"
  - SPF:
      labels:
        - '2023-05-23': "Santé Publique France"
  - AUTRE:
      labels:
        - '2023-05-23': "Autre"