ministeres:
  - MAA:
    - '2022-05-20': "Ministère de l'Agriculture et de la Souveraineté alimentaire"
    - '2020-07-06': "Ministère de l'Agriculture et de l'Alimentation"
  - MC:
    - '2020-07-06': "Ministère de la Culture"
  - MAS:
    - '2022-05-20': "Ministère de la Santé et de la Prévention"
    - '2020-07-06': "Ministère des Solidarités et de la Santé"
  - MSAPH:
    - '2022-05-20': "Ministère des Solidarités, de l'Autonomie et des personnes handicapées"
    - '2020-07-06': "Non attribué"
  - MTEI:
    - '2022-05-20': "Ministère du Travail, du Plein emploi et de l'Insertion"
    - '2020-07-06': "Ministère du Travail"
  - MEAE:
    - '2020-07-06': "Ministère de l'Europe et des Affaires étrangères"
  - MEF:
    - '2022-05-20': "Ministère de l'Économie, des Finances et de la Souveraineté industrielle et numérique"
    - '2020-07-06': "Ministère de l'Économie, des Finances et de la Relance"
  - MJS:
    - '2022-05-20': "Non attribué"
    - '2020-07-06': "Ministère de la Jeunesse et des Sports"
  - MSJO:
    - '2022-05-20': "Ministère des Sports et des Jeux olympiques et paralympiques"
    - '2020-07-06': "Non attribué"
  - MEN:
    - '2022-05-20': "Ministère de l'Éducation nationale et de la Jeunesse"
    - '2020-07-06': "Ministère de l'Éducation nationale, de la Jeunesse et des Sports"
  - ESR:
    - '2022-05-20': "Ministère de l'Enseignement supérieur et de la Recherche"
    - '2020-07-06': "Ministère de l'Enseignement supérieur, de la Recherche et de l'Innovation"
  - MI:
    - '2022-05-20': "Ministère de l'Intérieur et des Outre-mer"
    - '2020-07-06': "Ministère de l'Intérieur"
  - MINARM:
    - '2020-07-06': "Ministère des Armées"
  - MJ:
    - '2020-07-06': "Ministère de la Justice"
  - MTES:
    - '2022-05-20': "Ministère de la Transition écologique et de la Cohésion des territoires"
    - '2020-07-06': "Ministère de la Transition écologique"
  - MTE:
    - '2022-05-20': "Ministère de la Transition énergétique"
    - '2020-07-06': "Non attribué"
  - MCTRCT:
    - '2022-05-20': "Non attribué"
    - '2020-07-06': "Ministère de la Cohésion des territoires et des Relations avec les collectivités territoriales"
  - PM:
    - '2020-07-06': "Premier ministre"
  - MER:
    - '2022-05-20': "Non attribué"
    - '2020-07-06': "Ministère de la Mer"
  - MTFP:
    - '2020-07-06': "Ministère de la Transformation et de la Fonction publiques"
  - OM:
    - '2022-05-20': "Non attribué"
    - '2020-07-06': "Ministère des Outre-mer"
  - ARS ARA:
    label: "ARS Auvergne-Rhône-Alpes"
  - ARS BFC:
    label: "ARS Bourgogne-Franche-Comté"
  - ARS BRET:
    label: "ARS Bretagne"
  - ARS CVL:
    label: "ARS Centre-Val de Loire"
  - ARS COR:
    label: "ARS Corse"
  - ARS GE:
    label: "ARS Grand Est"
  - ARS GUAD:
    label: "ARS Guadeloupe"
  - ARS GUY:
    label: "ARS Guyane"
  - ARS HDF:
    label: "ARS Hauts-de-France"
  - ARS IF:
    label: "ARS Île-de-France"
  - ARS REU:
    label: "ARS La Réunion"
  - ARS MART:
    label: "ARS Martinique"
  - ARS MAY:
    label: "ARS Mayotte"
  - ARS NORM:
    label: "ARS Normandie"
  - ARS NA:
    label: "ARS Nouvelle-Aquitaine"
  - ARS OCC:
    label: "ARS Occitanie"
  - ARS PDL:
    label: "Pays de la Loire"
  - ARS PACA:
    label: "ARS Provence-Alpes-Côte d'Azur"
  - BCJS:
    label: "Bureau de la communication Jeunesse et sports"
  - DICOM:
    label: "Délégation à l'information et à la communication"
  - DAEI:
    label: "Délégation aux affaires européennes et internationales"
  - DSS:
    label: "Direction de la sécurité sociale"
  - DAJ:
    label: "Direction des affaires juridiques"
  - DFAS:
    label: "Direction des finances, des achats et des services"
  - DRH:
    label: "Direction des ressources humaines des ministères sociaux"
  - DNUM:
    label: "Direction du numérique"
  - DGOS:
    label: "Direction générale de l’offre de soins"
  - DGCS:
    label: "Direction générale de la cohésion sociale"
  - DGS:
    label: "Direction générale de la santé"
  - SG:
    label: "Secrétariat général des ministères chargés des affaires sociales"
  - SPF:
    label: Santé Publique France
  - AUTRE:
    lable: "Autre"
